// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CMD_TX`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> initLogger() => RustLib.instance.api.crateApiSimpleInitLogger();

Future<String> getCoreVersions() =>
    RustLib.instance.api.crateApiSimpleGetCoreVersions();

Stream<String> startEngine() =>
    RustLib.instance.api.crateApiSimpleStartEngine();

Future<void> registerSipAccount({
  required String targetIp,
  required int targetPort,
  required String user,
  required String password,
}) => RustLib.instance.api.crateApiSimpleRegisterSipAccount(
  targetIp: targetIp,
  targetPort: targetPort,
  user: user,
  password: password,
);

Future<void> startSipCall({
  required String targetIp,
  required int targetPort,
  required String toUser,
  required String fromUser,
}) => RustLib.instance.api.crateApiSimpleStartSipCall(
  targetIp: targetIp,
  targetPort: targetPort,
  toUser: toUser,
  fromUser: fromUser,
);

Future<void> acceptInboundCall() =>
    RustLib.instance.api.crateApiSimpleAcceptInboundCall();

Future<void> rejectInboundCall() =>
    RustLib.instance.api.crateApiSimpleRejectInboundCall();

Future<void> endSipCall() => RustLib.instance.api.crateApiSimpleEndSipCall();

Future<void> updateAudioSettings({
  required double micGain,
  required double speakerGain,
  required bool enableAec,
}) => RustLib.instance.api.crateApiSimpleUpdateAudioSettings(
  micGain: micGain,
  speakerGain: speakerGain,
  enableAec: enableAec,
);

Future<void> sendSipDtmf({required String key}) =>
    RustLib.instance.api.crateApiSimpleSendSipDtmf(key: key);

Future<void> setMute({required bool muted}) =>
    RustLib.instance.api.crateApiSimpleSetMute(muted: muted);
