// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CMD_TX`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> initLogger() => RustLib.instance.api.crateApiSimpleInitLogger();

/// Çağrıyı aniden kesmek için Flutter tarafından çağrılır.
Future<void> endSipCall() => RustLib.instance.api.crateApiSimpleEndSipCall();

Stream<String> startSipCall({
  required String targetIp,
  required int targetPort,
  required String toUser,
  required String fromUser,
}) => RustLib.instance.api.crateApiSimpleStartSipCall(
  targetIp: targetIp,
  targetPort: targetPort,
  toUser: toUser,
  fromUser: fromUser,
);

Future<void> updateAudioSettings({
  required double micGain,
  required double speakerGain,
  required bool enableAec,
}) => RustLib.instance.api.crateApiSimpleUpdateAudioSettings(
  micGain: micGain,
  speakerGain: speakerGain,
  enableAec: enableAec,
);
